# Dependabot configuration for automated dependency updates
# Version: 2
version: 2

updates:
  # Backend npm dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
    assignees:
      - "$REPO_OWNER"
    reviewers:
      - "$REPO_OWNER"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "typescript"
        versions: ["6.x"]

  # Frontend npm dependencies  
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
    assignees:
      - "$REPO_OWNER"
    reviewers:
      - "$REPO_OWNER"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
        update-types:
          - "major"
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "typescript"
        versions: ["6.x"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ci"
    assignees:
      - "$REPO_OWNER"
    reviewers:
      - "$REPO_OWNER"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"