/// <reference types="next" />
/// <reference types="react" />

// NOTE: This file is auto-generated by Next.js and should not be modified manually.
// Version compatibility: Next.js 14.0+

declare namespace NodeJS {
  interface ProcessEnv {
    readonly NODE_ENV: 'development' | 'production' | 'test'
    readonly NEXT_PUBLIC_SUPABASE_URL: string
    readonly NEXT_PUBLIC_SUPABASE_ANON_KEY: string
    readonly OPENAI_API_KEY: string
    readonly RESEND_API_KEY: string
    readonly DATABASE_URL: string
    readonly EDGE_CONFIG: string
    readonly VERCEL_ENV: 'production' | 'preview' | 'development'
    readonly VERCEL_URL: string
    readonly VERCEL_REGION: string
    [key: string]: string | undefined
  }
}

declare module '*.module.css' {
  const classes: { readonly [key: string]: string }
  export default classes
}

declare module '*.module.scss' {
  const classes: { readonly [key: string]: string }
  export default classes
}

declare module '*.module.sass' {
  const classes: { readonly [key: string]: string }
  export default classes
}

declare module '*.svg' {
  import * as React from 'react'
  const ReactComponent: React.FunctionComponent<React.SVGProps<SVGSVGElement>>
  export default ReactComponent
}

declare module '*.jpg' {
  const content: string
  export default content
}

declare module '*.png' {
  const content: string
  export default content
}

declare module '*.json' {
  const content: any
  export default content
}